
#General settings
[profiles]
	#Block to put underneath a bed so that it qualifies as a teleporter bed
	specialBedBlock = "minecraft:command_block"
	#The size of the todo queues for the lost city generator
	#Range: 1 ~ 100000
	todoQueueSize = 15

