
["Commands - /cleargrounditems"]
	"Enabled?" = false
	"Available in creative?" = false
	"Available in survival?" = false

["Enable or Disable Enchantments"]
	enhanced_protection = true
	enhanced_unbreaking = true
	Excavator = true
	Heavy = true
	Disengage = true
	Frostbite = true
	enhanced_handling = true
	lava_walker = true
	Smelting = true
	Feasting = true
	enhanced_sharpness = true
	Magnetize = true
	decay = true
	night_vision_ench = true
	lifestealing_arrows = true
	Delicate = true
	final_stand = true
	Vitality = true
	ground_pound = true
	blessed_weapon = true
	dull_edge = true
	swimmers_boots = true
	fiery_thorns = true
	midas_touch = true
	Springy = true
	enhanced_fire_aspect = true
	Spilling = true
	enhanced_locomotion = true
	enhanced_thorns = true
	tnt_miner = true
	Webbing = true
	xp_mining_master = true
	Wither = true
	"XP++ for Weapon" = true
	Lumberjack = true
	water_breathing = true
	jugger_nog = true
	enhanced_efficiency = true
	praise_the_sun = true
	exploding_arrows = true
	horse_shoe = true
	Savior = true
	Slowness = true
	insta_kill = true
	Lightning = true
	reverse_knockback = true
	"Enhanced Eff Arm Speed" = true

["Enable or disable explosions for enchantments"]
	Disengage = true
	tnt_miner = true
	ground_pound = true
	exploding_arrows = true

