//子弹标签
ServerEvents.tags('item', event => {
    event.add('newprovefrom:ammo', 'pointblank:ammocreative')
    event.add('newprovefrom:ammo', 'pointblank:ammo9mm')
    event.add('newprovefrom:ammo', 'pointblank:ammo45acp')
    event.add('newprovefrom:ammo', 'pointblank:ammo57')
    event.add('newprovefrom:ammo', 'pointblank:ammo357')
    event.add('newprovefrom:ammo', 'pointblank:ammo50ae')
    event.add('newprovefrom:ammo', 'pointblank:ammo46')
    event.add('newprovefrom:ammo', 'pointblank:ammo545')
    event.add('newprovefrom:ammo', 'pointblank:ammo556')
    event.add('newprovefrom:ammo', 'pointblank:ammo68')
    event.add('newprovefrom:ammo', 'pointblank:ammo762')
    event.add('newprovefrom:ammo', 'pointblank:ammo762x51')
    event.add('newprovefrom:ammo', 'pointblank:ammo338lapua')
    event.add('newprovefrom:ammo', 'pointblank:ammo50bmg')
    event.add('newprovefrom:ammo', 'pointblank:ammo12gauge')
    event.add('newprovefrom:ammo', 'pointblank:grenade40mm')
})